ALTER TABLE warehouses
    ADD COLUMN IF NOT EXISTS city VARCHAR(255) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS street VARCHAR(255) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS building VARCHAR(255) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS building2 VARCHAR(255) NOT NULL DEFAULT '';
