// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0--rc2
// source: catalog/catalog_service.proto

package catalog

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCategoryRequest) Reset() {
	*x = CreateCategoryRequest{}
	mi := &file_catalog_catalog_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCategoryRequest) ProtoMessage() {}

func (x *CreateCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_catalog_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCategoryRequest.ProtoReflect.Descriptor instead.
func (*CreateCategoryRequest) Descriptor() ([]byte, []int) {
	return file_catalog_catalog_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateCategoryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UpdateCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCategoryRequest) Reset() {
	*x = UpdateCategoryRequest{}
	mi := &file_catalog_catalog_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCategoryRequest) ProtoMessage() {}

func (x *UpdateCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_catalog_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCategoryRequest.ProtoReflect.Descriptor instead.
func (*UpdateCategoryRequest) Descriptor() ([]byte, []int) {
	return file_catalog_catalog_service_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateCategoryRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateCategoryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCategoryRequest) Reset() {
	*x = GetCategoryRequest{}
	mi := &file_catalog_catalog_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCategoryRequest) ProtoMessage() {}

func (x *GetCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_catalog_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCategoryRequest.ProtoReflect.Descriptor instead.
func (*GetCategoryRequest) Descriptor() ([]byte, []int) {
	return file_catalog_catalog_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetCategoryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetListCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListCategoryRequest) Reset() {
	*x = GetListCategoryRequest{}
	mi := &file_catalog_catalog_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListCategoryRequest) ProtoMessage() {}

func (x *GetListCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_catalog_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListCategoryRequest.ProtoReflect.Descriptor instead.
func (*GetListCategoryRequest) Descriptor() ([]byte, []int) {
	return file_catalog_catalog_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetListCategoryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetListCategoryRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type DeleteCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCategoryRequest) Reset() {
	*x = DeleteCategoryRequest{}
	mi := &file_catalog_catalog_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCategoryRequest) ProtoMessage() {}

func (x *DeleteCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_catalog_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCategoryRequest.ProtoReflect.Descriptor instead.
func (*DeleteCategoryRequest) Descriptor() ([]byte, []int) {
	return file_catalog_catalog_service_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteCategoryRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Category struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Category) Reset() {
	*x = Category{}
	mi := &file_catalog_catalog_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Category) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category) ProtoMessage() {}

func (x *Category) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_catalog_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category.ProtoReflect.Descriptor instead.
func (*Category) Descriptor() ([]byte, []int) {
	return file_catalog_catalog_service_proto_rawDescGZIP(), []int{5}
}

func (x *Category) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Category) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListCategoriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      []*Category            `protobuf:"bytes,1,rep,name=category,proto3" json:"category,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCategoriesResponse) Reset() {
	*x = ListCategoriesResponse{}
	mi := &file_catalog_catalog_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCategoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCategoriesResponse) ProtoMessage() {}

func (x *ListCategoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_catalog_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCategoriesResponse.ProtoReflect.Descriptor instead.
func (*ListCategoriesResponse) Descriptor() ([]byte, []int) {
	return file_catalog_catalog_service_proto_rawDescGZIP(), []int{6}
}

func (x *ListCategoriesResponse) GetCategory() []*Category {
	if x != nil {
		return x.Category
	}
	return nil
}

func (x *ListCategoriesResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type CreateProductRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ManufacturerId uint64                 `protobuf:"varint,2,opt,name=manufacturer_id,json=manufacturerId,proto3" json:"manufacturer_id,omitempty"`
	CategoryId     uint64                 `protobuf:"varint,3,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Price          float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateProductRequest) Reset() {
	*x = CreateProductRequest{}
	mi := &file_catalog_catalog_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductRequest) ProtoMessage() {}

func (x *CreateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_catalog_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductRequest.ProtoReflect.Descriptor instead.
func (*CreateProductRequest) Descriptor() ([]byte, []int) {
	return file_catalog_catalog_service_proto_rawDescGZIP(), []int{7}
}

func (x *CreateProductRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateProductRequest) GetManufacturerId() uint64 {
	if x != nil {
		return x.ManufacturerId
	}
	return 0
}

func (x *CreateProductRequest) GetCategoryId() uint64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *CreateProductRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type UpdateProductRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ManufacturerId uint64                 `protobuf:"varint,3,opt,name=manufacturer_id,json=manufacturerId,proto3" json:"manufacturer_id,omitempty"`
	CategoryId     uint64                 `protobuf:"varint,4,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Price          float64                `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateProductRequest) Reset() {
	*x = UpdateProductRequest{}
	mi := &file_catalog_catalog_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductRequest) ProtoMessage() {}

func (x *UpdateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_catalog_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductRequest.ProtoReflect.Descriptor instead.
func (*UpdateProductRequest) Descriptor() ([]byte, []int) {
	return file_catalog_catalog_service_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateProductRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateProductRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateProductRequest) GetManufacturerId() uint64 {
	if x != nil {
		return x.ManufacturerId
	}
	return 0
}

func (x *UpdateProductRequest) GetCategoryId() uint64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *UpdateProductRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type GetProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductRequest) Reset() {
	*x = GetProductRequest{}
	mi := &file_catalog_catalog_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductRequest) ProtoMessage() {}

func (x *GetProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_catalog_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductRequest.ProtoReflect.Descriptor instead.
func (*GetProductRequest) Descriptor() ([]byte, []int) {
	return file_catalog_catalog_service_proto_rawDescGZIP(), []int{9}
}

func (x *GetProductRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetProductByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductByIDRequest) Reset() {
	*x = GetProductByIDRequest{}
	mi := &file_catalog_catalog_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductByIDRequest) ProtoMessage() {}

func (x *GetProductByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_catalog_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductByIDRequest.ProtoReflect.Descriptor instead.
func (*GetProductByIDRequest) Descriptor() ([]byte, []int) {
	return file_catalog_catalog_service_proto_rawDescGZIP(), []int{10}
}

func (x *GetProductByIDRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetListProductRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Limit          int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset         int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	CategoryId     uint64                 `protobuf:"varint,3,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	ManufacturerId uint64                 `protobuf:"varint,4,opt,name=manufacturer_id,json=manufacturerId,proto3" json:"manufacturer_id,omitempty"`
	PriceMin       float64                `protobuf:"fixed64,5,opt,name=price_min,json=priceMin,proto3" json:"price_min,omitempty"`
	PriceMax       float64                `protobuf:"fixed64,6,opt,name=price_max,json=priceMax,proto3" json:"price_max,omitempty"`
	NameContains   string                 `protobuf:"bytes,7,opt,name=name_contains,json=nameContains,proto3" json:"name_contains,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetListProductRequest) Reset() {
	*x = GetListProductRequest{}
	mi := &file_catalog_catalog_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListProductRequest) ProtoMessage() {}

func (x *GetListProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_catalog_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListProductRequest.ProtoReflect.Descriptor instead.
func (*GetListProductRequest) Descriptor() ([]byte, []int) {
	return file_catalog_catalog_service_proto_rawDescGZIP(), []int{11}
}

func (x *GetListProductRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetListProductRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetListProductRequest) GetCategoryId() uint64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *GetListProductRequest) GetManufacturerId() uint64 {
	if x != nil {
		return x.ManufacturerId
	}
	return 0
}

func (x *GetListProductRequest) GetPriceMin() float64 {
	if x != nil {
		return x.PriceMin
	}
	return 0
}

func (x *GetListProductRequest) GetPriceMax() float64 {
	if x != nil {
		return x.PriceMax
	}
	return 0
}

func (x *GetListProductRequest) GetNameContains() string {
	if x != nil {
		return x.NameContains
	}
	return ""
}

type DeleteProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProductRequest) Reset() {
	*x = DeleteProductRequest{}
	mi := &file_catalog_catalog_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProductRequest) ProtoMessage() {}

func (x *DeleteProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_catalog_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProductRequest.ProtoReflect.Descriptor instead.
func (*DeleteProductRequest) Descriptor() ([]byte, []int) {
	return file_catalog_catalog_service_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteProductRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Product struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ManufacturerId uint64                 `protobuf:"varint,3,opt,name=manufacturer_id,json=manufacturerId,proto3" json:"manufacturer_id,omitempty"`
	CategoryId     uint64                 `protobuf:"varint,4,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Price          float64                `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_catalog_catalog_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_catalog_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_catalog_catalog_service_proto_rawDescGZIP(), []int{13}
}

func (x *Product) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetManufacturerId() uint64 {
	if x != nil {
		return x.ManufacturerId
	}
	return 0
}

func (x *Product) GetCategoryId() uint64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *Product) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type ListProductsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       []*Product             `protobuf:"bytes,1,rep,name=product,proto3" json:"product,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsResponse) Reset() {
	*x = ListProductsResponse{}
	mi := &file_catalog_catalog_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsResponse) ProtoMessage() {}

func (x *ListProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_catalog_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsResponse.ProtoReflect.Descriptor instead.
func (*ListProductsResponse) Descriptor() ([]byte, []int) {
	return file_catalog_catalog_service_proto_rawDescGZIP(), []int{14}
}

func (x *ListProductsResponse) GetProduct() []*Product {
	if x != nil {
		return x.Product
	}
	return nil
}

func (x *ListProductsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type CreateManufacturerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateManufacturerRequest) Reset() {
	*x = CreateManufacturerRequest{}
	mi := &file_catalog_catalog_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateManufacturerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateManufacturerRequest) ProtoMessage() {}

func (x *CreateManufacturerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_catalog_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateManufacturerRequest.ProtoReflect.Descriptor instead.
func (*CreateManufacturerRequest) Descriptor() ([]byte, []int) {
	return file_catalog_catalog_service_proto_rawDescGZIP(), []int{15}
}

func (x *CreateManufacturerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UpdateManufacturerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateManufacturerRequest) Reset() {
	*x = UpdateManufacturerRequest{}
	mi := &file_catalog_catalog_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateManufacturerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateManufacturerRequest) ProtoMessage() {}

func (x *UpdateManufacturerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_catalog_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateManufacturerRequest.ProtoReflect.Descriptor instead.
func (*UpdateManufacturerRequest) Descriptor() ([]byte, []int) {
	return file_catalog_catalog_service_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateManufacturerRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateManufacturerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetManufacturerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetManufacturerRequest) Reset() {
	*x = GetManufacturerRequest{}
	mi := &file_catalog_catalog_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetManufacturerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetManufacturerRequest) ProtoMessage() {}

func (x *GetManufacturerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_catalog_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetManufacturerRequest.ProtoReflect.Descriptor instead.
func (*GetManufacturerRequest) Descriptor() ([]byte, []int) {
	return file_catalog_catalog_service_proto_rawDescGZIP(), []int{17}
}

func (x *GetManufacturerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetListManufacturerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListManufacturerRequest) Reset() {
	*x = GetListManufacturerRequest{}
	mi := &file_catalog_catalog_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListManufacturerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListManufacturerRequest) ProtoMessage() {}

func (x *GetListManufacturerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_catalog_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListManufacturerRequest.ProtoReflect.Descriptor instead.
func (*GetListManufacturerRequest) Descriptor() ([]byte, []int) {
	return file_catalog_catalog_service_proto_rawDescGZIP(), []int{18}
}

func (x *GetListManufacturerRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetListManufacturerRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type DeleteManufacturerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteManufacturerRequest) Reset() {
	*x = DeleteManufacturerRequest{}
	mi := &file_catalog_catalog_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteManufacturerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteManufacturerRequest) ProtoMessage() {}

func (x *DeleteManufacturerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_catalog_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteManufacturerRequest.ProtoReflect.Descriptor instead.
func (*DeleteManufacturerRequest) Descriptor() ([]byte, []int) {
	return file_catalog_catalog_service_proto_rawDescGZIP(), []int{19}
}

func (x *DeleteManufacturerRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Manufacturer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Manufacturer) Reset() {
	*x = Manufacturer{}
	mi := &file_catalog_catalog_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Manufacturer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Manufacturer) ProtoMessage() {}

func (x *Manufacturer) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_catalog_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Manufacturer.ProtoReflect.Descriptor instead.
func (*Manufacturer) Descriptor() ([]byte, []int) {
	return file_catalog_catalog_service_proto_rawDescGZIP(), []int{20}
}

func (x *Manufacturer) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Manufacturer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListManufacturerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Manufacturer  []*Manufacturer        `protobuf:"bytes,1,rep,name=manufacturer,proto3" json:"manufacturer,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListManufacturerResponse) Reset() {
	*x = ListManufacturerResponse{}
	mi := &file_catalog_catalog_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListManufacturerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListManufacturerResponse) ProtoMessage() {}

func (x *ListManufacturerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_catalog_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListManufacturerResponse.ProtoReflect.Descriptor instead.
func (*ListManufacturerResponse) Descriptor() ([]byte, []int) {
	return file_catalog_catalog_service_proto_rawDescGZIP(), []int{21}
}

func (x *ListManufacturerResponse) GetManufacturer() []*Manufacturer {
	if x != nil {
		return x.Manufacturer
	}
	return nil
}

func (x *ListManufacturerResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_catalog_catalog_service_proto protoreflect.FileDescriptor

const file_catalog_catalog_service_proto_rawDesc = "" +
	"\n" +
	"\x1dcatalog/catalog_service.proto\x12\acatalog\x1a\x1bgoogle/protobuf/empty.proto\"+\n" +
	"\x15CreateCategoryRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\";\n" +
	"\x15UpdateCategoryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"(\n" +
	"\x12GetCategoryRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"F\n" +
	"\x16GetListCategoryRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"'\n" +
	"\x15DeleteCategoryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\".\n" +
	"\bCategory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"]\n" +
	"\x16ListCategoriesResponse\x12-\n" +
	"\bcategory\x18\x01 \x03(\v2\x11.catalog.CategoryR\bcategory\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\x8a\x01\n" +
	"\x14CreateProductRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12'\n" +
	"\x0fmanufacturer_id\x18\x02 \x01(\x04R\x0emanufacturerId\x12\x1f\n" +
	"\vcategory_id\x18\x03 \x01(\x04R\n" +
	"categoryId\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\"\x9a\x01\n" +
	"\x14UpdateProductRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12'\n" +
	"\x0fmanufacturer_id\x18\x03 \x01(\x04R\x0emanufacturerId\x12\x1f\n" +
	"\vcategory_id\x18\x04 \x01(\x04R\n" +
	"categoryId\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x01R\x05price\"'\n" +
	"\x11GetProductRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"'\n" +
	"\x15GetProductByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"\xee\x01\n" +
	"\x15GetListProductRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\x12\x1f\n" +
	"\vcategory_id\x18\x03 \x01(\x04R\n" +
	"categoryId\x12'\n" +
	"\x0fmanufacturer_id\x18\x04 \x01(\x04R\x0emanufacturerId\x12\x1b\n" +
	"\tprice_min\x18\x05 \x01(\x01R\bpriceMin\x12\x1b\n" +
	"\tprice_max\x18\x06 \x01(\x01R\bpriceMax\x12#\n" +
	"\rname_contains\x18\a \x01(\tR\fnameContains\"&\n" +
	"\x14DeleteProductRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"\x8d\x01\n" +
	"\aProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12'\n" +
	"\x0fmanufacturer_id\x18\x03 \x01(\x04R\x0emanufacturerId\x12\x1f\n" +
	"\vcategory_id\x18\x04 \x01(\x04R\n" +
	"categoryId\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x01R\x05price\"X\n" +
	"\x14ListProductsResponse\x12*\n" +
	"\aproduct\x18\x01 \x03(\v2\x10.catalog.ProductR\aproduct\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"/\n" +
	"\x19CreateManufacturerRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"?\n" +
	"\x19UpdateManufacturerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\",\n" +
	"\x16GetManufacturerRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"J\n" +
	"\x1aGetListManufacturerRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"+\n" +
	"\x19DeleteManufacturerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"2\n" +
	"\fManufacturer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"k\n" +
	"\x18ListManufacturerResponse\x129\n" +
	"\fmanufacturer\x18\x01 \x03(\v2\x15.catalog.ManufacturerR\fmanufacturer\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total2\xb4\t\n" +
	"\x0eCatalogService\x12C\n" +
	"\x0eCreateCategory\x12\x1e.catalog.CreateCategoryRequest\x1a\x11.catalog.Category\x12C\n" +
	"\x0eUpdateCategory\x12\x1e.catalog.UpdateCategoryRequest\x1a\x11.catalog.Category\x12=\n" +
	"\vGetCategory\x12\x1b.catalog.GetCategoryRequest\x1a\x11.catalog.Category\x12S\n" +
	"\x0fGetListCategory\x12\x1f.catalog.GetListCategoryRequest\x1a\x1f.catalog.ListCategoriesResponse\x12H\n" +
	"\x0eDeleteCategory\x12\x1e.catalog.DeleteCategoryRequest\x1a\x16.google.protobuf.Empty\x12@\n" +
	"\rCreateProduct\x12\x1d.catalog.CreateProductRequest\x1a\x10.catalog.Product\x12@\n" +
	"\rUpdateProduct\x12\x1d.catalog.UpdateProductRequest\x1a\x10.catalog.Product\x12F\n" +
	"\rDeleteProduct\x12\x1d.catalog.DeleteProductRequest\x1a\x16.google.protobuf.Empty\x12:\n" +
	"\n" +
	"GetProduct\x12\x1a.catalog.GetProductRequest\x1a\x10.catalog.Product\x12B\n" +
	"\x0eGetProductByID\x12\x1e.catalog.GetProductByIDRequest\x1a\x10.catalog.Product\x12O\n" +
	"\x0eGetListProduct\x12\x1e.catalog.GetListProductRequest\x1a\x1d.catalog.ListProductsResponse\x12O\n" +
	"\x12CreateManufacturer\x12\".catalog.CreateManufacturerRequest\x1a\x15.catalog.Manufacturer\x12O\n" +
	"\x12UpdateManufacturer\x12\".catalog.UpdateManufacturerRequest\x1a\x15.catalog.Manufacturer\x12I\n" +
	"\x0fGetManufacturer\x12\x1f.catalog.GetManufacturerRequest\x1a\x15.catalog.Manufacturer\x12^\n" +
	"\x14GetListManufacturers\x12#.catalog.GetListManufacturerRequest\x1a!.catalog.ListManufacturerResponse\x12P\n" +
	"\x12DeleteManufacturer\x12\".catalog.DeleteManufacturerRequest\x1a\x16.google.protobuf.EmptyB\x1dZ\x1bkinos/proto/catalog;catalogb\x06proto3"

var (
	file_catalog_catalog_service_proto_rawDescOnce sync.Once
	file_catalog_catalog_service_proto_rawDescData []byte
)

func file_catalog_catalog_service_proto_rawDescGZIP() []byte {
	file_catalog_catalog_service_proto_rawDescOnce.Do(func() {
		file_catalog_catalog_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_catalog_catalog_service_proto_rawDesc), len(file_catalog_catalog_service_proto_rawDesc)))
	})
	return file_catalog_catalog_service_proto_rawDescData
}

var file_catalog_catalog_service_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_catalog_catalog_service_proto_goTypes = []any{
	(*CreateCategoryRequest)(nil),      // 0: catalog.CreateCategoryRequest
	(*UpdateCategoryRequest)(nil),      // 1: catalog.UpdateCategoryRequest
	(*GetCategoryRequest)(nil),         // 2: catalog.GetCategoryRequest
	(*GetListCategoryRequest)(nil),     // 3: catalog.GetListCategoryRequest
	(*DeleteCategoryRequest)(nil),      // 4: catalog.DeleteCategoryRequest
	(*Category)(nil),                   // 5: catalog.Category
	(*ListCategoriesResponse)(nil),     // 6: catalog.ListCategoriesResponse
	(*CreateProductRequest)(nil),       // 7: catalog.CreateProductRequest
	(*UpdateProductRequest)(nil),       // 8: catalog.UpdateProductRequest
	(*GetProductRequest)(nil),          // 9: catalog.GetProductRequest
	(*GetProductByIDRequest)(nil),      // 10: catalog.GetProductByIDRequest
	(*GetListProductRequest)(nil),      // 11: catalog.GetListProductRequest
	(*DeleteProductRequest)(nil),       // 12: catalog.DeleteProductRequest
	(*Product)(nil),                    // 13: catalog.Product
	(*ListProductsResponse)(nil),       // 14: catalog.ListProductsResponse
	(*CreateManufacturerRequest)(nil),  // 15: catalog.CreateManufacturerRequest
	(*UpdateManufacturerRequest)(nil),  // 16: catalog.UpdateManufacturerRequest
	(*GetManufacturerRequest)(nil),     // 17: catalog.GetManufacturerRequest
	(*GetListManufacturerRequest)(nil), // 18: catalog.GetListManufacturerRequest
	(*DeleteManufacturerRequest)(nil),  // 19: catalog.DeleteManufacturerRequest
	(*Manufacturer)(nil),               // 20: catalog.Manufacturer
	(*ListManufacturerResponse)(nil),   // 21: catalog.ListManufacturerResponse
	(*emptypb.Empty)(nil),              // 22: google.protobuf.Empty
}
var file_catalog_catalog_service_proto_depIdxs = []int32{
	5,  // 0: catalog.ListCategoriesResponse.category:type_name -> catalog.Category
	13, // 1: catalog.ListProductsResponse.product:type_name -> catalog.Product
	20, // 2: catalog.ListManufacturerResponse.manufacturer:type_name -> catalog.Manufacturer
	0,  // 3: catalog.CatalogService.CreateCategory:input_type -> catalog.CreateCategoryRequest
	1,  // 4: catalog.CatalogService.UpdateCategory:input_type -> catalog.UpdateCategoryRequest
	2,  // 5: catalog.CatalogService.GetCategory:input_type -> catalog.GetCategoryRequest
	3,  // 6: catalog.CatalogService.GetListCategory:input_type -> catalog.GetListCategoryRequest
	4,  // 7: catalog.CatalogService.DeleteCategory:input_type -> catalog.DeleteCategoryRequest
	7,  // 8: catalog.CatalogService.CreateProduct:input_type -> catalog.CreateProductRequest
	8,  // 9: catalog.CatalogService.UpdateProduct:input_type -> catalog.UpdateProductRequest
	12, // 10: catalog.CatalogService.DeleteProduct:input_type -> catalog.DeleteProductRequest
	9,  // 11: catalog.CatalogService.GetProduct:input_type -> catalog.GetProductRequest
	10, // 12: catalog.CatalogService.GetProductByID:input_type -> catalog.GetProductByIDRequest
	11, // 13: catalog.CatalogService.GetListProduct:input_type -> catalog.GetListProductRequest
	15, // 14: catalog.CatalogService.CreateManufacturer:input_type -> catalog.CreateManufacturerRequest
	16, // 15: catalog.CatalogService.UpdateManufacturer:input_type -> catalog.UpdateManufacturerRequest
	17, // 16: catalog.CatalogService.GetManufacturer:input_type -> catalog.GetManufacturerRequest
	18, // 17: catalog.CatalogService.GetListManufacturers:input_type -> catalog.GetListManufacturerRequest
	19, // 18: catalog.CatalogService.DeleteManufacturer:input_type -> catalog.DeleteManufacturerRequest
	5,  // 19: catalog.CatalogService.CreateCategory:output_type -> catalog.Category
	5,  // 20: catalog.CatalogService.UpdateCategory:output_type -> catalog.Category
	5,  // 21: catalog.CatalogService.GetCategory:output_type -> catalog.Category
	6,  // 22: catalog.CatalogService.GetListCategory:output_type -> catalog.ListCategoriesResponse
	22, // 23: catalog.CatalogService.DeleteCategory:output_type -> google.protobuf.Empty
	13, // 24: catalog.CatalogService.CreateProduct:output_type -> catalog.Product
	13, // 25: catalog.CatalogService.UpdateProduct:output_type -> catalog.Product
	22, // 26: catalog.CatalogService.DeleteProduct:output_type -> google.protobuf.Empty
	13, // 27: catalog.CatalogService.GetProduct:output_type -> catalog.Product
	13, // 28: catalog.CatalogService.GetProductByID:output_type -> catalog.Product
	14, // 29: catalog.CatalogService.GetListProduct:output_type -> catalog.ListProductsResponse
	20, // 30: catalog.CatalogService.CreateManufacturer:output_type -> catalog.Manufacturer
	20, // 31: catalog.CatalogService.UpdateManufacturer:output_type -> catalog.Manufacturer
	20, // 32: catalog.CatalogService.GetManufacturer:output_type -> catalog.Manufacturer
	21, // 33: catalog.CatalogService.GetListManufacturers:output_type -> catalog.ListManufacturerResponse
	22, // 34: catalog.CatalogService.DeleteManufacturer:output_type -> google.protobuf.Empty
	19, // [19:35] is the sub-list for method output_type
	3,  // [3:19] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_catalog_catalog_service_proto_init() }
func file_catalog_catalog_service_proto_init() {
	if File_catalog_catalog_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_catalog_catalog_service_proto_rawDesc), len(file_catalog_catalog_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_catalog_catalog_service_proto_goTypes,
		DependencyIndexes: file_catalog_catalog_service_proto_depIdxs,
		MessageInfos:      file_catalog_catalog_service_proto_msgTypes,
	}.Build()
	File_catalog_catalog_service_proto = out.File
	file_catalog_catalog_service_proto_goTypes = nil
	file_catalog_catalog_service_proto_depIdxs = nil
}
