// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0--rc2
// source: inventory_service.proto

package inventory

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Запросы для управления запасами
type CreateInventoryRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ProductId         uint64                 `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity          int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	WarehouseLocation string                 `protobuf:"bytes,3,opt,name=warehouse_location,json=warehouseLocation,proto3" json:"warehouse_location,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateInventoryRequest) Reset() {
	*x = CreateInventoryRequest{}
	mi := &file_inventory_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInventoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInventoryRequest) ProtoMessage() {}

func (x *CreateInventoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInventoryRequest.ProtoReflect.Descriptor instead.
func (*CreateInventoryRequest) Descriptor() ([]byte, []int) {
	return file_inventory_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateInventoryRequest) GetProductId() uint64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *CreateInventoryRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *CreateInventoryRequest) GetWarehouseLocation() string {
	if x != nil {
		return x.WarehouseLocation
	}
	return ""
}

type UpdateInventoryRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Quantity          int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	WarehouseLocation string                 `protobuf:"bytes,3,opt,name=warehouse_location,json=warehouseLocation,proto3" json:"warehouse_location,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UpdateInventoryRequest) Reset() {
	*x = UpdateInventoryRequest{}
	mi := &file_inventory_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateInventoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateInventoryRequest) ProtoMessage() {}

func (x *UpdateInventoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateInventoryRequest.ProtoReflect.Descriptor instead.
func (*UpdateInventoryRequest) Descriptor() ([]byte, []int) {
	return file_inventory_service_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateInventoryRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateInventoryRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *UpdateInventoryRequest) GetWarehouseLocation() string {
	if x != nil {
		return x.WarehouseLocation
	}
	return ""
}

type GetInventoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     uint64                 `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInventoryRequest) Reset() {
	*x = GetInventoryRequest{}
	mi := &file_inventory_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInventoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInventoryRequest) ProtoMessage() {}

func (x *GetInventoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInventoryRequest.ProtoReflect.Descriptor instead.
func (*GetInventoryRequest) Descriptor() ([]byte, []int) {
	return file_inventory_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetInventoryRequest) GetProductId() uint64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

type GetListInventoryRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Limit             int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset            int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	ProductId         uint64                 `protobuf:"varint,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	WarehouseLocation string                 `protobuf:"bytes,4,opt,name=warehouse_location,json=warehouseLocation,proto3" json:"warehouse_location,omitempty"`
	MinQuantity       int32                  `protobuf:"varint,5,opt,name=min_quantity,json=minQuantity,proto3" json:"min_quantity,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetListInventoryRequest) Reset() {
	*x = GetListInventoryRequest{}
	mi := &file_inventory_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListInventoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListInventoryRequest) ProtoMessage() {}

func (x *GetListInventoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListInventoryRequest.ProtoReflect.Descriptor instead.
func (*GetListInventoryRequest) Descriptor() ([]byte, []int) {
	return file_inventory_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetListInventoryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetListInventoryRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetListInventoryRequest) GetProductId() uint64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *GetListInventoryRequest) GetWarehouseLocation() string {
	if x != nil {
		return x.WarehouseLocation
	}
	return ""
}

func (x *GetListInventoryRequest) GetMinQuantity() int32 {
	if x != nil {
		return x.MinQuantity
	}
	return 0
}

type DeleteInventoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteInventoryRequest) Reset() {
	*x = DeleteInventoryRequest{}
	mi := &file_inventory_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteInventoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteInventoryRequest) ProtoMessage() {}

func (x *DeleteInventoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteInventoryRequest.ProtoReflect.Descriptor instead.
func (*DeleteInventoryRequest) Descriptor() ([]byte, []int) {
	return file_inventory_service_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteInventoryRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// Запросы для резервирования
type ReserveStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     uint64                 `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	ReservationId string                 `protobuf:"bytes,3,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveStockRequest) Reset() {
	*x = ReserveStockRequest{}
	mi := &file_inventory_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveStockRequest) ProtoMessage() {}

func (x *ReserveStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveStockRequest.ProtoReflect.Descriptor instead.
func (*ReserveStockRequest) Descriptor() ([]byte, []int) {
	return file_inventory_service_proto_rawDescGZIP(), []int{5}
}

func (x *ReserveStockRequest) GetProductId() uint64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *ReserveStockRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *ReserveStockRequest) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

type ReleaseReservationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     uint64                 `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ReservationId string                 `protobuf:"bytes,2,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseReservationRequest) Reset() {
	*x = ReleaseReservationRequest{}
	mi := &file_inventory_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseReservationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseReservationRequest) ProtoMessage() {}

func (x *ReleaseReservationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseReservationRequest.ProtoReflect.Descriptor instead.
func (*ReleaseReservationRequest) Descriptor() ([]byte, []int) {
	return file_inventory_service_proto_rawDescGZIP(), []int{6}
}

func (x *ReleaseReservationRequest) GetProductId() uint64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *ReleaseReservationRequest) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

// Запросы для управления складами
type CreateWarehouseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	City          string                 `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	Street        string                 `protobuf:"bytes,3,opt,name=street,proto3" json:"street,omitempty"`
	Building      string                 `protobuf:"bytes,4,opt,name=building,proto3" json:"building,omitempty"`
	Building2     string                 `protobuf:"bytes,5,opt,name=building2,proto3" json:"building2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWarehouseRequest) Reset() {
	*x = CreateWarehouseRequest{}
	mi := &file_inventory_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWarehouseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWarehouseRequest) ProtoMessage() {}

func (x *CreateWarehouseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWarehouseRequest.ProtoReflect.Descriptor instead.
func (*CreateWarehouseRequest) Descriptor() ([]byte, []int) {
	return file_inventory_service_proto_rawDescGZIP(), []int{7}
}

func (x *CreateWarehouseRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateWarehouseRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *CreateWarehouseRequest) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *CreateWarehouseRequest) GetBuilding() string {
	if x != nil {
		return x.Building
	}
	return ""
}

func (x *CreateWarehouseRequest) GetBuilding2() string {
	if x != nil {
		return x.Building2
	}
	return ""
}

type UpdateWarehouseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	City          string                 `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	Street        string                 `protobuf:"bytes,4,opt,name=street,proto3" json:"street,omitempty"`
	Building      string                 `protobuf:"bytes,5,opt,name=building,proto3" json:"building,omitempty"`
	Building2     string                 `protobuf:"bytes,6,opt,name=building2,proto3" json:"building2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateWarehouseRequest) Reset() {
	*x = UpdateWarehouseRequest{}
	mi := &file_inventory_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWarehouseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWarehouseRequest) ProtoMessage() {}

func (x *UpdateWarehouseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWarehouseRequest.ProtoReflect.Descriptor instead.
func (*UpdateWarehouseRequest) Descriptor() ([]byte, []int) {
	return file_inventory_service_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateWarehouseRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateWarehouseRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateWarehouseRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *UpdateWarehouseRequest) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *UpdateWarehouseRequest) GetBuilding() string {
	if x != nil {
		return x.Building
	}
	return ""
}

func (x *UpdateWarehouseRequest) GetBuilding2() string {
	if x != nil {
		return x.Building2
	}
	return ""
}

type GetListWarehouseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListWarehouseRequest) Reset() {
	*x = GetListWarehouseRequest{}
	mi := &file_inventory_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListWarehouseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListWarehouseRequest) ProtoMessage() {}

func (x *GetListWarehouseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListWarehouseRequest.ProtoReflect.Descriptor instead.
func (*GetListWarehouseRequest) Descriptor() ([]byte, []int) {
	return file_inventory_service_proto_rawDescGZIP(), []int{9}
}

func (x *GetListWarehouseRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetListWarehouseRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type DeleteWarehouseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWarehouseRequest) Reset() {
	*x = DeleteWarehouseRequest{}
	mi := &file_inventory_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWarehouseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWarehouseRequest) ProtoMessage() {}

func (x *DeleteWarehouseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWarehouseRequest.ProtoReflect.Descriptor instead.
func (*DeleteWarehouseRequest) Descriptor() ([]byte, []int) {
	return file_inventory_service_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteWarehouseRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// Ответы для складов
type Warehouse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	City          string                 `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	Street        string                 `protobuf:"bytes,4,opt,name=street,proto3" json:"street,omitempty"`
	Building      string                 `protobuf:"bytes,5,opt,name=building,proto3" json:"building,omitempty"`
	Building2     string                 `protobuf:"bytes,6,opt,name=building2,proto3" json:"building2,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Warehouse) Reset() {
	*x = Warehouse{}
	mi := &file_inventory_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Warehouse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Warehouse) ProtoMessage() {}

func (x *Warehouse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Warehouse.ProtoReflect.Descriptor instead.
func (*Warehouse) Descriptor() ([]byte, []int) {
	return file_inventory_service_proto_rawDescGZIP(), []int{11}
}

func (x *Warehouse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Warehouse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Warehouse) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Warehouse) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *Warehouse) GetBuilding() string {
	if x != nil {
		return x.Building
	}
	return ""
}

func (x *Warehouse) GetBuilding2() string {
	if x != nil {
		return x.Building2
	}
	return ""
}

func (x *Warehouse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Warehouse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type ListWarehouseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Warehouses    []*Warehouse           `protobuf:"bytes,1,rep,name=warehouses,proto3" json:"warehouses,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWarehouseResponse) Reset() {
	*x = ListWarehouseResponse{}
	mi := &file_inventory_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWarehouseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWarehouseResponse) ProtoMessage() {}

func (x *ListWarehouseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWarehouseResponse.ProtoReflect.Descriptor instead.
func (*ListWarehouseResponse) Descriptor() ([]byte, []int) {
	return file_inventory_service_proto_rawDescGZIP(), []int{12}
}

func (x *ListWarehouseResponse) GetWarehouses() []*Warehouse {
	if x != nil {
		return x.Warehouses
	}
	return nil
}

func (x *ListWarehouseResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// Ответы
type Inventory struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId         uint64                 `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity          int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	ReservedQuantity  int32                  `protobuf:"varint,4,opt,name=reserved_quantity,json=reservedQuantity,proto3" json:"reserved_quantity,omitempty"`
	AvailableQuantity int32                  `protobuf:"varint,5,opt,name=available_quantity,json=availableQuantity,proto3" json:"available_quantity,omitempty"`
	WarehouseLocation string                 `protobuf:"bytes,6,opt,name=warehouse_location,json=warehouseLocation,proto3" json:"warehouse_location,omitempty"`
	UpdatedAt         string                 `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Inventory) Reset() {
	*x = Inventory{}
	mi := &file_inventory_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Inventory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Inventory) ProtoMessage() {}

func (x *Inventory) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Inventory.ProtoReflect.Descriptor instead.
func (*Inventory) Descriptor() ([]byte, []int) {
	return file_inventory_service_proto_rawDescGZIP(), []int{13}
}

func (x *Inventory) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Inventory) GetProductId() uint64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *Inventory) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Inventory) GetReservedQuantity() int32 {
	if x != nil {
		return x.ReservedQuantity
	}
	return 0
}

func (x *Inventory) GetAvailableQuantity() int32 {
	if x != nil {
		return x.AvailableQuantity
	}
	return 0
}

func (x *Inventory) GetWarehouseLocation() string {
	if x != nil {
		return x.WarehouseLocation
	}
	return ""
}

func (x *Inventory) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type ListInventoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inventory     []*Inventory           `protobuf:"bytes,1,rep,name=inventory,proto3" json:"inventory,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInventoryResponse) Reset() {
	*x = ListInventoryResponse{}
	mi := &file_inventory_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInventoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInventoryResponse) ProtoMessage() {}

func (x *ListInventoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInventoryResponse.ProtoReflect.Descriptor instead.
func (*ListInventoryResponse) Descriptor() ([]byte, []int) {
	return file_inventory_service_proto_rawDescGZIP(), []int{14}
}

func (x *ListInventoryResponse) GetInventory() []*Inventory {
	if x != nil {
		return x.Inventory
	}
	return nil
}

func (x *ListInventoryResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ReserveStockResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Success          bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ReservationId    string                 `protobuf:"bytes,2,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	ReservedQuantity int32                  `protobuf:"varint,3,opt,name=reserved_quantity,json=reservedQuantity,proto3" json:"reserved_quantity,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ReserveStockResponse) Reset() {
	*x = ReserveStockResponse{}
	mi := &file_inventory_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveStockResponse) ProtoMessage() {}

func (x *ReserveStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveStockResponse.ProtoReflect.Descriptor instead.
func (*ReserveStockResponse) Descriptor() ([]byte, []int) {
	return file_inventory_service_proto_rawDescGZIP(), []int{15}
}

func (x *ReserveStockResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReserveStockResponse) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *ReserveStockResponse) GetReservedQuantity() int32 {
	if x != nil {
		return x.ReservedQuantity
	}
	return 0
}

type ReleaseReservationResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Success          bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ReleasedQuantity int32                  `protobuf:"varint,2,opt,name=released_quantity,json=releasedQuantity,proto3" json:"released_quantity,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ReleaseReservationResponse) Reset() {
	*x = ReleaseReservationResponse{}
	mi := &file_inventory_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseReservationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseReservationResponse) ProtoMessage() {}

func (x *ReleaseReservationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseReservationResponse.ProtoReflect.Descriptor instead.
func (*ReleaseReservationResponse) Descriptor() ([]byte, []int) {
	return file_inventory_service_proto_rawDescGZIP(), []int{16}
}

func (x *ReleaseReservationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReleaseReservationResponse) GetReleasedQuantity() int32 {
	if x != nil {
		return x.ReleasedQuantity
	}
	return 0
}

var File_inventory_service_proto protoreflect.FileDescriptor

const file_inventory_service_proto_rawDesc = "" +
	"\n" +
	"\x17inventory_service.proto\x12\tinventory\x1a\x1bgoogle/protobuf/empty.proto\"\x82\x01\n" +
	"\x16CreateInventoryRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x04R\tproductId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\x12-\n" +
	"\x12warehouse_location\x18\x03 \x01(\tR\x11warehouseLocation\"s\n" +
	"\x16UpdateInventoryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\x12-\n" +
	"\x12warehouse_location\x18\x03 \x01(\tR\x11warehouseLocation\"4\n" +
	"\x13GetInventoryRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x04R\tproductId\"\xb8\x01\n" +
	"\x17GetListInventoryRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\x12\x1d\n" +
	"\n" +
	"product_id\x18\x03 \x01(\x04R\tproductId\x12-\n" +
	"\x12warehouse_location\x18\x04 \x01(\tR\x11warehouseLocation\x12!\n" +
	"\fmin_quantity\x18\x05 \x01(\x05R\vminQuantity\"(\n" +
	"\x16DeleteInventoryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"w\n" +
	"\x13ReserveStockRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x04R\tproductId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\x12%\n" +
	"\x0ereservation_id\x18\x03 \x01(\tR\rreservationId\"a\n" +
	"\x19ReleaseReservationRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x04R\tproductId\x12%\n" +
	"\x0ereservation_id\x18\x02 \x01(\tR\rreservationId\"\x92\x01\n" +
	"\x16CreateWarehouseRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04city\x18\x02 \x01(\tR\x04city\x12\x16\n" +
	"\x06street\x18\x03 \x01(\tR\x06street\x12\x1a\n" +
	"\bbuilding\x18\x04 \x01(\tR\bbuilding\x12\x1c\n" +
	"\tbuilding2\x18\x05 \x01(\tR\tbuilding2\"\xa2\x01\n" +
	"\x16UpdateWarehouseRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04city\x18\x03 \x01(\tR\x04city\x12\x16\n" +
	"\x06street\x18\x04 \x01(\tR\x06street\x12\x1a\n" +
	"\bbuilding\x18\x05 \x01(\tR\bbuilding\x12\x1c\n" +
	"\tbuilding2\x18\x06 \x01(\tR\tbuilding2\"G\n" +
	"\x17GetListWarehouseRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"(\n" +
	"\x16DeleteWarehouseRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"\xd3\x01\n" +
	"\tWarehouse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04city\x18\x03 \x01(\tR\x04city\x12\x16\n" +
	"\x06street\x18\x04 \x01(\tR\x06street\x12\x1a\n" +
	"\bbuilding\x18\x05 \x01(\tR\bbuilding\x12\x1c\n" +
	"\tbuilding2\x18\x06 \x01(\tR\tbuilding2\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\tR\tupdatedAt\"c\n" +
	"\x15ListWarehouseResponse\x124\n" +
	"\n" +
	"warehouses\x18\x01 \x03(\v2\x14.inventory.WarehouseR\n" +
	"warehouses\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\x80\x02\n" +
	"\tInventory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\x04R\tproductId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\x12+\n" +
	"\x11reserved_quantity\x18\x04 \x01(\x05R\x10reservedQuantity\x12-\n" +
	"\x12available_quantity\x18\x05 \x01(\x05R\x11availableQuantity\x12-\n" +
	"\x12warehouse_location\x18\x06 \x01(\tR\x11warehouseLocation\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAt\"a\n" +
	"\x15ListInventoryResponse\x122\n" +
	"\tinventory\x18\x01 \x03(\v2\x14.inventory.InventoryR\tinventory\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\x84\x01\n" +
	"\x14ReserveStockResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12%\n" +
	"\x0ereservation_id\x18\x02 \x01(\tR\rreservationId\x12+\n" +
	"\x11reserved_quantity\x18\x03 \x01(\x05R\x10reservedQuantity\"c\n" +
	"\x1aReleaseReservationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12+\n" +
	"\x11released_quantity\x18\x02 \x01(\x05R\x10releasedQuantity2\x8c\a\n" +
	"\x10InventoryService\x12J\n" +
	"\x0fCreateInventory\x12!.inventory.CreateInventoryRequest\x1a\x14.inventory.Inventory\x12J\n" +
	"\x0fUpdateInventory\x12!.inventory.UpdateInventoryRequest\x1a\x14.inventory.Inventory\x12D\n" +
	"\fGetInventory\x12\x1e.inventory.GetInventoryRequest\x1a\x14.inventory.Inventory\x12X\n" +
	"\x10GetListInventory\x12\".inventory.GetListInventoryRequest\x1a .inventory.ListInventoryResponse\x12L\n" +
	"\x0fDeleteInventory\x12!.inventory.DeleteInventoryRequest\x1a\x16.google.protobuf.Empty\x12O\n" +
	"\fReserveStock\x12\x1e.inventory.ReserveStockRequest\x1a\x1f.inventory.ReserveStockResponse\x12a\n" +
	"\x12ReleaseReservation\x12$.inventory.ReleaseReservationRequest\x1a%.inventory.ReleaseReservationResponse\x12J\n" +
	"\x0fCreateWarehouse\x12!.inventory.CreateWarehouseRequest\x1a\x14.inventory.Warehouse\x12J\n" +
	"\x0fUpdateWarehouse\x12!.inventory.UpdateWarehouseRequest\x1a\x14.inventory.Warehouse\x12X\n" +
	"\x10GetListWarehouse\x12\".inventory.GetListWarehouseRequest\x1a .inventory.ListWarehouseResponse\x12L\n" +
	"\x0fDeleteWarehouse\x12!.inventory.DeleteWarehouseRequest\x1a\x16.google.protobuf.EmptyB6Z4github.com/ilnurcode/Kinos/proto/inventory;inventoryb\x06proto3"

var (
	file_inventory_service_proto_rawDescOnce sync.Once
	file_inventory_service_proto_rawDescData []byte
)

func file_inventory_service_proto_rawDescGZIP() []byte {
	file_inventory_service_proto_rawDescOnce.Do(func() {
		file_inventory_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_inventory_service_proto_rawDesc), len(file_inventory_service_proto_rawDesc)))
	})
	return file_inventory_service_proto_rawDescData
}

var file_inventory_service_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_inventory_service_proto_goTypes = []any{
	(*CreateInventoryRequest)(nil),     // 0: inventory.CreateInventoryRequest
	(*UpdateInventoryRequest)(nil),     // 1: inventory.UpdateInventoryRequest
	(*GetInventoryRequest)(nil),        // 2: inventory.GetInventoryRequest
	(*GetListInventoryRequest)(nil),    // 3: inventory.GetListInventoryRequest
	(*DeleteInventoryRequest)(nil),     // 4: inventory.DeleteInventoryRequest
	(*ReserveStockRequest)(nil),        // 5: inventory.ReserveStockRequest
	(*ReleaseReservationRequest)(nil),  // 6: inventory.ReleaseReservationRequest
	(*CreateWarehouseRequest)(nil),     // 7: inventory.CreateWarehouseRequest
	(*UpdateWarehouseRequest)(nil),     // 8: inventory.UpdateWarehouseRequest
	(*GetListWarehouseRequest)(nil),    // 9: inventory.GetListWarehouseRequest
	(*DeleteWarehouseRequest)(nil),     // 10: inventory.DeleteWarehouseRequest
	(*Warehouse)(nil),                  // 11: inventory.Warehouse
	(*ListWarehouseResponse)(nil),      // 12: inventory.ListWarehouseResponse
	(*Inventory)(nil),                  // 13: inventory.Inventory
	(*ListInventoryResponse)(nil),      // 14: inventory.ListInventoryResponse
	(*ReserveStockResponse)(nil),       // 15: inventory.ReserveStockResponse
	(*ReleaseReservationResponse)(nil), // 16: inventory.ReleaseReservationResponse
	(*emptypb.Empty)(nil),              // 17: google.protobuf.Empty
}
var file_inventory_service_proto_depIdxs = []int32{
	11, // 0: inventory.ListWarehouseResponse.warehouses:type_name -> inventory.Warehouse
	13, // 1: inventory.ListInventoryResponse.inventory:type_name -> inventory.Inventory
	0,  // 2: inventory.InventoryService.CreateInventory:input_type -> inventory.CreateInventoryRequest
	1,  // 3: inventory.InventoryService.UpdateInventory:input_type -> inventory.UpdateInventoryRequest
	2,  // 4: inventory.InventoryService.GetInventory:input_type -> inventory.GetInventoryRequest
	3,  // 5: inventory.InventoryService.GetListInventory:input_type -> inventory.GetListInventoryRequest
	4,  // 6: inventory.InventoryService.DeleteInventory:input_type -> inventory.DeleteInventoryRequest
	5,  // 7: inventory.InventoryService.ReserveStock:input_type -> inventory.ReserveStockRequest
	6,  // 8: inventory.InventoryService.ReleaseReservation:input_type -> inventory.ReleaseReservationRequest
	7,  // 9: inventory.InventoryService.CreateWarehouse:input_type -> inventory.CreateWarehouseRequest
	8,  // 10: inventory.InventoryService.UpdateWarehouse:input_type -> inventory.UpdateWarehouseRequest
	9,  // 11: inventory.InventoryService.GetListWarehouse:input_type -> inventory.GetListWarehouseRequest
	10, // 12: inventory.InventoryService.DeleteWarehouse:input_type -> inventory.DeleteWarehouseRequest
	13, // 13: inventory.InventoryService.CreateInventory:output_type -> inventory.Inventory
	13, // 14: inventory.InventoryService.UpdateInventory:output_type -> inventory.Inventory
	13, // 15: inventory.InventoryService.GetInventory:output_type -> inventory.Inventory
	14, // 16: inventory.InventoryService.GetListInventory:output_type -> inventory.ListInventoryResponse
	17, // 17: inventory.InventoryService.DeleteInventory:output_type -> google.protobuf.Empty
	15, // 18: inventory.InventoryService.ReserveStock:output_type -> inventory.ReserveStockResponse
	16, // 19: inventory.InventoryService.ReleaseReservation:output_type -> inventory.ReleaseReservationResponse
	11, // 20: inventory.InventoryService.CreateWarehouse:output_type -> inventory.Warehouse
	11, // 21: inventory.InventoryService.UpdateWarehouse:output_type -> inventory.Warehouse
	12, // 22: inventory.InventoryService.GetListWarehouse:output_type -> inventory.ListWarehouseResponse
	17, // 23: inventory.InventoryService.DeleteWarehouse:output_type -> google.protobuf.Empty
	13, // [13:24] is the sub-list for method output_type
	2,  // [2:13] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_inventory_service_proto_init() }
func file_inventory_service_proto_init() {
	if File_inventory_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_inventory_service_proto_rawDesc), len(file_inventory_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_inventory_service_proto_goTypes,
		DependencyIndexes: file_inventory_service_proto_depIdxs,
		MessageInfos:      file_inventory_service_proto_msgTypes,
	}.Build()
	File_inventory_service_proto = out.File
	file_inventory_service_proto_goTypes = nil
	file_inventory_service_proto_depIdxs = nil
}
